#!/usr/bin/env bun
/**
 * PAI Setup Ensurer
 * 
 * Ensures all required components are installed and configured.
 * Auto-fixes common issues where possible.
 * 
 * Usage:
 *   bun run docxology/scripts/ensure-setup.ts
 *   bun run docxology/scripts/ensure-setup.ts --fix
 */

import { existsSync, mkdirSync, writeFileSync, readFileSync, chmodSync } from 'fs';
import { join } from 'path';
import { homedir } from 'os';

const PAI_DIR = process.env.PAI_DIR || join(homedir(), '.claude');
const FIX_MODE = process.argv.includes('--fix');

console.log('\n🔧 PAI Setup Ensurer\n');
console.log(`PAI_DIR: ${PAI_DIR}`);
console.log(`Mode: ${FIX_MODE ? 'Fix' : 'Check Only'}\n`);

let fixesApplied = 0;

function ensureDir(path: string, name: string): void {
  if (!existsSync(path)) {
    if (FIX_MODE) {
      mkdirSync(path, { recursive: true });
      console.log(`✓ Created ${name}`);
      fixesApplied++;
    } else {
      console.log(`✗ Missing ${name} (run with --fix to create)`);
    }
  } else {
    console.log(`✓ ${name} exists`);
  }
}

function ensureFile(path: string, content: string, name: string): void {
  if (!existsSync(path)) {
    if (FIX_MODE) {
      writeFileSync(path, content);
      console.log(`✓ Created ${name}`);
      fixesApplied++;
    } else {
      console.log(`✗ Missing ${name} (run with --fix to create)`);
    }
  } else {
    console.log(`✓ ${name} exists`);
  }
}

// 1. Ensure PAI directory structure
console.log('📁 Directory Structure');
console.log('─'.repeat(50));

ensureDir(PAI_DIR, 'PAI Directory');
ensureDir(join(PAI_DIR, 'hooks'), 'Hooks Directory');
ensureDir(join(PAI_DIR, 'hooks', 'lib'), 'Hooks Lib Directory');
ensureDir(join(PAI_DIR, 'skills'), 'Skills Directory');
ensureDir(join(PAI_DIR, 'skills', 'CORE'), 'CORE Skill Directory');
ensureDir(join(PAI_DIR, 'history'), 'History Directory');
ensureDir(join(PAI_DIR, 'history', 'sessions'), 'Sessions Directory');
ensureDir(join(PAI_DIR, 'history', 'learnings'), 'Learnings Directory');
ensureDir(join(PAI_DIR, 'history', 'research'), 'Research Directory');
ensureDir(join(PAI_DIR, 'history', 'decisions'), 'Decisions Directory');
ensureDir(join(PAI_DIR, 'history', 'raw-outputs'), 'Raw Outputs Directory');
ensureDir(join(PAI_DIR, 'tools'), 'Tools Directory');
ensureDir(join(PAI_DIR, 'voice'), 'Voice Directory');
ensureDir(join(PAI_DIR, 'observability'), 'Observability Directory');

console.log('');

// 2. Ensure .env file
console.log('⚙️  Configuration Files');
console.log('─'.repeat(50));

const envPath = join(PAI_DIR, '.env');
if (!existsSync(envPath)) {
  if (FIX_MODE) {
    const defaultEnv = `# PAI Environment Configuration
# Generated by ensure-setup.ts

DA=Tet
TIME_ZONE=America/Los_Angeles
PAI_DIR=${PAI_DIR}
PAI_SOURCE_APP=Tet

# Add your API keys below:
# ELEVENLABS_API_KEY=your_key_here
# GOOGLE_API_KEY=your_key_here
# REPLICATE_API_TOKEN=your_token_here
`;
    writeFileSync(envPath, defaultEnv);
    console.log('✓ Created .env file with defaults');
    fixesApplied++;
  } else {
    console.log('✗ Missing .env file (run with --fix to create)');
  }
} else {
  console.log('✓ .env file exists');
  
  // Check for required variables
  if (FIX_MODE) {
    try {
      const envContent = readFileSync(envPath, 'utf-8');
      let updated = false;
      let newContent = envContent;
      
      if (!envContent.includes('DA=')) {
        newContent += '\nDA=Tet\n';
        updated = true;
      }
      if (!envContent.includes('TIME_ZONE=')) {
        newContent += 'TIME_ZONE=America/Los_Angeles\n';
        updated = true;
      }
      if (!envContent.includes('PAI_DIR=')) {
        newContent += `PAI_DIR=${PAI_DIR}\n`;
        updated = true;
      }
      
      if (updated) {
        writeFileSync(envPath, newContent);
        console.log('✓ Updated .env with missing variables');
        fixesApplied++;
      }
    } catch (e) {
      console.log(`⚠ Could not read/update .env: ${e}`);
    }
  }
}

// 3. Ensure settings.json has hooks
console.log('');
console.log('🪝 Hook Configuration');
console.log('─'.repeat(50));

const settingsPath = join(homedir(), '.claude', 'settings.json');
if (existsSync(settingsPath)) {
  try {
    const settings = JSON.parse(readFileSync(settingsPath, 'utf-8'));
    if (!settings.hooks || Object.keys(settings.hooks).length === 0) {
      if (FIX_MODE) {
        console.log('⚠ settings.json exists but has no hooks - manual configuration required');
        console.log('   See: Packs/kai-hook-system/config/settings-hooks.json');
      } else {
        console.log('✗ settings.json has no hooks configured');
      }
    } else {
      console.log(`✓ Hooks configured (${Object.keys(settings.hooks).length} event types)`);
    }
  } catch (e) {
    console.log(`✗ settings.json is invalid JSON: ${e}`);
  }
} else {
  console.log('✗ settings.json missing (run Kai Bundle installer)');
}

console.log('');

// 4. Ensure skill index exists
console.log('📚 Skill System');
console.log('─'.repeat(50));

const skillIndexPath = join(PAI_DIR, 'skills', 'skill-index.json');
if (!existsSync(skillIndexPath)) {
  if (FIX_MODE) {
    console.log('⚠ Skill index missing - generating...');
    try {
      const result = Bun.spawnSync([
        'bun', 'run', join(PAI_DIR, 'tools', 'GenerateSkillIndex.ts')
      ], {
        stdout: 'pipe',
        stderr: 'pipe',
        env: { ...process.env, PAI_DIR }
      });

      if (result.exitCode === 0) {
        console.log('✓ Generated skill index');
        fixesApplied++;
      } else {
        console.log('✗ Failed to generate skill index');
      }
    } catch (e) {
      console.log(`✗ Error generating skill index: ${e}`);
    }
  } else {
    console.log('✗ Skill index missing (run with --fix to generate)');
  }
} else {
  console.log('✓ Skill index exists');
}

console.log('');

// 5. Ensure manage script is executable
console.log('🔧 Scripts');
console.log('─'.repeat(50));

const manageScript = join(PAI_DIR, 'observability', 'manage.sh');
if (existsSync(manageScript)) {
  try {
    const stats = require('fs').statSync(manageScript);
    if ((stats.mode & parseInt('111', 8)) === 0) {
      if (FIX_MODE) {
        chmodSync(manageScript, '755');
        console.log('✓ Made manage.sh executable');
        fixesApplied++;
      } else {
        console.log('✗ manage.sh is not executable (run with --fix)');
      }
    } else {
      console.log('✓ manage.sh is executable');
    }
  } catch (e) {
    console.log(`⚠ Could not check manage.sh: ${e}`);
  }
} else {
  console.log('⚠ manage.sh not found (observability server not installed?)');
}

console.log('');

// Summary
console.log('─'.repeat(50));
if (FIX_MODE) {
  if (fixesApplied > 0) {
    console.log(`\n✅ Applied ${fixesApplied} fix(es)\n`);
  } else {
    console.log('\n✅ No fixes needed - system is properly configured\n');
  }
} else {
  console.log('\n💡 Run with --fix to automatically fix issues\n');
}
